import { api, setToken } from "./api.js";
const groupSelect=document.querySelector("#groupSelect"),library=document.querySelector("#library"),formMessage=document.querySelector("#formMessage"),inspectButton=document.querySelector("#inspectButton"),metadataPreview=document.querySelector("#metadataPreview");
function esc(value=""){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
async function loadGroups(){const groups=await api("/api/v1/groups");groupSelect.innerHTML=groups.map(g=>`<option value="${esc(g.id)}">${esc(g.name)}</option>`).join("");if(!groups.length)throw new Error("No perteneces a ningún grupo activo.")}
async function loadDashboard(){const d=await api(`/api/v1/groups/${groupSelect.value}/dashboard`);document.querySelector("#total").textContent=d.total;document.querySelector("#month").textContent=d.month;document.querySelector("#members").textContent=d.members;document.querySelector("#commentCount").textContent=d.comments}
function queryString(){const values={q:document.querySelector("#search").value.trim(),platform:document.querySelector("#platform").value,type:document.querySelector("#type").value,genre:document.querySelector("#genreFilter").value.trim()};const p=new URLSearchParams(Object.entries(values).filter(([,v])=>v));return p.toString()?`?${p}`:""}
function cover(i){return i.imageUrl?`<img class="cover" src="${esc(i.imageUrl)}" alt="" loading="lazy">`:`<div class="cover cover-placeholder" aria-hidden="true">♫</div>`}
async function loadLibrary(){const items=await api(`/api/v1/groups/${groupSelect.value}/music${queryString()}`);library.innerHTML=items.length?items.map(i=>`<article class="music-card" data-id="${esc(i.id)}"><div class="music-main">${cover(i)}<div class="music-copy"><p class="eyebrow platform-${esc(i.platform)}">${esc(i.platform)} · ${esc(i.type)}</p><h3><a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.title)}</a></h3><p class="artist">${esc(i.artist||"Artista sin indicar")}</p><div class="meta">${i.genre?`<span class="chip">${esc(i.genre)}</span>`:""}<span class="chip">por ${esc(i.addedBy)}</span><span class="chip">${new Date(i.addedAt).toLocaleDateString()}</span></div></div></div><div class="music-footer"><div class="rating">${[1,2,3,4,5].map(v=>`<button type="button" data-rating="${v}" title="${v} estrellas">${v<=Math.round(i.rating)?"★":"☆"}</button>`).join("")}<small>${Number(i.rating).toFixed(1)} · ${i.votes} votos</small></div><small class="muted">${i.comments} comentarios</small></div><details><summary>Abrir conversación</summary><div class="comments"></div><form class="comment-form"><input name="body" required maxlength="4000" placeholder="Escribe un comentario"><button class="button button-secondary">Publicar</button></form></details></article>`).join(""):`<p class="empty-state">No hay resultados con estos filtros.</p>`}
async function refresh(){try{await Promise.all([loadDashboard(),loadLibrary()])}catch(e){library.textContent=e.message}}
async function inspectUrl(){const raw=document.querySelector("#musicUrl").value.trim();if(!raw)return;inspectButton.disabled=true;inspectButton.textContent="Buscando…";formMessage.textContent="Consultando los datos del enlace…";try{const d=await api("/api/v1/links/metadata",{method:"POST",body:JSON.stringify({url:raw})});document.querySelector("#musicUrl").value=d.url||raw;if(d.title)document.querySelector("#title").value=d.title;if(d.artist)document.querySelector("#artist").value=d.artist;document.querySelector("#imageUrl").value=d.imageUrl||"";metadataPreview.hidden=false;metadataPreview.className="metadata-preview";metadataPreview.innerHTML=`${d.imageUrl?`<img src="${esc(d.imageUrl)}" alt="">`:`<div class="cover cover-placeholder">♫</div>`}<div><strong>${esc(d.title||"Enlace reconocido")}</strong><p class="muted">${esc(d.artist||`${d.platform} · ${d.type}`)}</p></div>`;formMessage.textContent=d.title?"Datos completados. Puedes corregirlos antes de guardar.":"Enlace reconocido; completa los campos que falten."}catch(e){formMessage.textContent=e.message}finally{inspectButton.disabled=false;inspectButton.textContent="Completar"}}
async function loadComments(card){const cs=await api(`/api/v1/music/${card.dataset.id}/comments`);card.querySelector(".comments").innerHTML=cs.length?cs.map(c=>`<p><strong>${esc(c.displayName)}</strong>: ${esc(c.body)}<br><small class="muted">${new Date(c.createdAt).toLocaleString()}</small></p>`).join(""):'<p class="muted">Todavía no hay comentarios.</p>'}
inspectButton.addEventListener("click",inspectUrl);document.querySelector("#musicUrl").addEventListener("paste",()=>setTimeout(inspectUrl,50));
document.querySelector("#musicForm").addEventListener("submit",async e=>{e.preventDefault();formMessage.textContent="Guardando…";try{await api(`/api/v1/groups/${groupSelect.value}/music`,{method:"POST",body:JSON.stringify({url:document.querySelector("#musicUrl").value.trim(),title:document.querySelector("#title").value.trim(),artist:document.querySelector("#artist").value.trim(),genre:document.querySelector("#genre").value.trim(),comment:document.querySelector("#comment").value.trim(),imageUrl:document.querySelector("#imageUrl").value.trim()})});e.target.reset();metadataPreview.hidden=true;formMessage.textContent="Guardada en la biblioteca.";await refresh()}catch(err){formMessage.textContent=err.message}});
document.querySelector("#filters").addEventListener("submit",e=>{e.preventDefault();loadLibrary()});document.querySelector("#search").addEventListener("input",()=>{clearTimeout(window.searchTimer);window.searchTimer=setTimeout(loadLibrary,250)});groupSelect.addEventListener("change",refresh);
library.addEventListener("click",async e=>{const card=e.target.closest(".music-card");if(!card)return;if(e.target.dataset.rating){await api(`/api/v1/music/${card.dataset.id}/rating`,{method:"PUT",body:JSON.stringify({value:Number(e.target.dataset.rating)})});await loadLibrary()}});
library.addEventListener("toggle",e=>{const d=e.target;if(d.tagName==="DETAILS"&&d.open)loadComments(d.closest(".music-card"))},true);
library.addEventListener("submit",async e=>{if(!e.target.matches(".comment-form"))return;e.preventDefault();const card=e.target.closest(".music-card"),input=e.target.elements.body;await api(`/api/v1/music/${card.dataset.id}/comments`,{method:"POST",body:JSON.stringify({body:input.value.trim()})});input.value="";await loadComments(card);await loadDashboard()});
document.querySelector("#logout").addEventListener("click",()=>{setToken("");location.href="./login.html"});(async()=>{try{await loadGroups();await refresh()}catch(e){library.textContent=e.message}})();